# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# Required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=52.1.16
forge_version_range=[52,)
loader_version_range=[52,)
mapping_channel=official
mapping_version=1.21.1

## Mod Properties

mod_id=minedar
mod_name=MiNEDAR
mod_license=MIT
mod_version=0.2.0
mod_group_id=dev.minedar
mod_authors=ransombiyato
mod_description=Client-side Minecraft LiDAR. Scans real world geometry, entities, particles and fluids into a persistent, material-aware point cloud with a live density minimap.
